language: node_js     
node_js:
- "6.7.0"
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: 
- git config user.email "travis@seekdesign.fr";git config user.name "Travis deployment"
- git remote set-url origin https://${GH_TOKEN}@${GH_REF} /dev/null 2>&1
- git fetch --all
- gulp build:gh-pages
cache:
  directories:
  - node_modules
  - bower_components
